USE adlister_db;

DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  username VARCHAR(255),
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255),
PRIMARY KEY (id)
);


DROP TABLE IF EXISTS ads;

CREATE TABLE IF NOT EXISTS ads (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id INT UNSIGNED NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT,
PRIMARY KEY (id),
FOREIGN KEY (user_id) REFERENCES
users(id)
);

